services:

  mongo:
    image: mongo:7
    container_name: popcard_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-popcard}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: popcard_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret}
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: popcard_api
    restart: unless-stopped
    ports:
      - "3010:3010"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-secret}@mongo:27017/${MONGO_DB:-popcard}?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
    depends_on:
      - mongo
      - redis
    command: node src/index.js

  worker:
    build: .
    container_name: popcard_worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-secret}@mongo:27017/${MONGO_DB:-popcard}?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
    depends_on:
      - mongo
      - redis
    command: node src/workers/points-award.worker.js

volumes:
  mongo_data:
  redis_data: